### ISSUE TITLE
Build tool agnostic solution using BSP

### ISSUE THREAD

**Issue by Fristi** [scalacenter/sbt-dependency-graph-action#37]
Cool plugin!

This implementation is tied to sbt, but other build tools which support building scala like mill, bazel, maven and gradle could talk via _BSP_ to extract the dependency graph?

Aside from that this solution is also tied to Github, while other organizations might be using AzureDevOps, Gitlab, etc where this 'matrix' might also be included? So segregating the reporting interface and making implementations for these might be cool :)

**Comment by adpi2** [comment]
Thanks for opening this discussion.

I am sympathetic to extending this Github action for other build tools like Mill, Bazel, Gradle and scala-cli, and I would even try to do so in this repository, after renaming it to `scala-dependency-graph-action`. I never tried before but I think it is possible to have several Github action in the same repo, with this syntax at use site:
```yaml
## for sbt
- uses: scalacenter/scala-dependency-graph-action/sbt@v1
## for Mill
- uses: scalacenter/scala-dependency-graph-action/mill@v1
```

Would it be possible or better to use BSP to extract the dependencies? I think we would lose some power and flexibility, but still it is probably worth exploring. This would be a good solution for scala-cli.

```
## for BSP
- uses: scalacenter/scala-dependency-graph-action/bsp@v1
```

I know that @ckipp01 has started working on version for Mill.

This repository is a Github action and I am not considering extending it for other hosting services like Azure, Gitlab. If there is a part of this repository that could be reused for other services, like for instance a BSP dependency extractor, we can make them available as a package on Maven or npm.

**Comment by adpi2** [comment]
For a BSP dependency extractor, we could do something like this:
- Try to find a BSP compatible build tool in the repo (a `*.sbt` file for sbt, a `mill` file for Mill) or fall back to scala-cli
- Run the corresponding command to generate the `.bsp` configuration
- Start the BSP server, send a 'workspace/buildTargets` to extract all the dependencies
- Transform the `workspace/buildTargets` response into a Github snapshot
- Submit it to Github

I will probably not have time to work on this any time soon. Does someone want to help?

**Comment by Fristi** [comment]
At the scala-steward project there is research going also to use BSP.  See: https://github.com/scala-steward-org/scala-steward/issues/2640

In sbt we were not able to extract the dependencies becase `buildTarget/dependencyModules` is not supported yet. I opened a ticket for that: https://github.com/sbt/sbt/issues/6957

In mill it is supported, but we are lacking the *resolvers* in scala-steward. I've opened a proposal to implement that in the protocol https://github.com/build-server-protocol/build-server-protocol/issues/344

**Comment by ckipp01** [comment]
This is an interesting idea. I didn't think about using BSP for this, but it might work, although bit more complex to just get all the moving pieces working.

Regarding the points up above from @adpi2, we actually do something similiar in Metals where if we detect a supported build tool and we know it's a BSP server, then we know how to generate a `.bsp/<entry.json>` for it. We could do something very similiar here.

One thing I noticed while looking through the spec for `buildTarget/dependencyModules` is that under `data` it mentions looking at the `MavenDependencyModule` as an example. That has some useful stuff under it like `scope` for example that we might want to capture, but I don't see that option under the Scala extension. Do we have enough on the Scala side to also easily parse out whether it's a direct or indirect dependency as well?

**Comment by Fristi** [comment]
Is this still relevant, otherwise we could close this?
